### ISSUE TITLE
Cannot enable Vim mode in latest Xcode

### ISSUE THREAD

**Issue by txiangyang** [XVimProject/XVim2#126] opened 2018-04-02 13:06 UTC
[Write issue description here]

```
-------- Debug Info -------
XVim2 revision : 66c6dc44edfca8a032b78294a03721ee7c51dd95
OS Version : Version 10.13.4 (Build 17E199)
Xcode Version : 9.3

--- .xvimrc ---
N/A
--------------
```

**Comment by theyongdai** [comment] 2018-04-02 13:37
This is dupe of [issue122](https://github.com/XVimProject/XVim2/issues/122), although there's a workaround at moment. ![image](https://user-images.githubusercontent.com/2506034/38198073-3bb74742-3659-11e8-8840-a5a872212bd5.png)

Cheers

**Comment by DarcyC** [comment] 2018-04-03 02:57
+1 
my OS Version 10.13.4, Xcode Version: 9.3.
I'm trying to download Release 9.3, then 'make', but "build failed" in the terminal.
Build in Xcode, error:

clang: error: no such file or directory: '/Users/lancelot/Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Versions/A/DVTKit'
clang: error: no such file or directory: '/Users/lancelot/Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/IDEKit'
clang: error: no such file or directory: '/Users/lancelot/Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation'
clang: error: no such file or directory: '/Users/lancelot/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation'

**Comment by pebble8888** [comment] 2018-04-06 12:26
Fixed in develop branch.
If you have any problem, please write detail.

**Closed by pebble8888** 2018-04-06 12:26 UTC
Labels: duplicate
