### ISSUE TITLE
Editor -> XVim

### ISSUE THREAD

**Issue by louwe** [XVimProject/XVim2#26] opened 2017-10-12 21:05 UTC
So XVim used to have Editor -> XVim menu to enable/disable the plugin.
This is useful during code reviews or paired programming sessions when I could potentially have another person who has no idea on how to use vim to still be able to use my computer without getting extremely frustrated.

I've noticed under XVim2 that this menu no longer exists. Did it get moved somewhere I didn't notice or is it still on a future road map?

**Comment by dcasadevall** [comment] 2017-10-12 22:37
> This is useful during code reviews or paired programming sessions when I could potentially have another person who has no idea on how to use vim to still be able to use my computer without getting extremely frustrated.

"Working as intended"! That other person should learn VIM :p

**Comment by antmd** [comment] 2017-10-14 12:23
I've committed a change to bring back the XVim menu (with the 'enable' option). It's now under the 'Edit' menu, because the 'Editor' menu didn't work for some reason (probably because it get's rebuilt depending on context). Please pull and try.

**Comment by antmd** [comment] 2017-10-16 15:33
Closing. Let me know if it doesn't work.

**Closed by antmd** 2017-10-16 15:33 UTC

**Comment by louwe** [comment] 2017-10-17 15:24
Works great in latest master, thanks!
