### ISSUE TITLE
Xcode crashes when performing operation towards the end of the file

### ISSUE THREAD

**Issue by pman215** [XVimProject/XVim2#27] opened 2017-10-12 23:06 UTC
## Issue Description: 

When rapidly moving up an down towards the end of a file using the `j` and `k` keys Xcode crashes. This bug has happened twice already

## Configuration

- Build compiled base of the following commit 828d4cf
- xcode-select version 2347
- Xcode 9

## Steps To Reproduce:

1. Open a file
2. Go towards the end of a file and move up and down. 

Sometimes I was deleting and yanking the last method of the file to move it up and the crash happened.

## Stack Trace

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
ProductBuildVersion: 9A235

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.dt.SourceEditor     	0x000000012a2e5e9d _T012SourceEditor0ab4DataA0C30positionFromInternalCharOffsetAA0aB8PositionVSi_Si8lineHinttF + 1789
1   com.apple.dt.IDE.IDEPegasusSourceEditor	0x0000000129e7de46 _T022IDEPegasusSourceEditor0b4CodeC4ViewC17selectedTextRangeSC8_NSRangeVfsTf4xn_n + 326
2   com.apple.dt.IDE.IDEPegasusSourceEditor	0x0000000129e744b7 _T022IDEPegasusSourceEditor0b4CodeC4ViewC17selectedTextRangeSC8_NSRangeVfsTo + 39
3   net.JugglerShu.XVim2          	0x0000000127a633c8 -[SourceCodeEditorViewProxy setSelectedRanges:affinity:stillSelecting:] + 163 (SourceCodeEditorViewProxy.m:276)
4   net.JugglerShu.XVim2          	0x0000000127a4ec8c -[SourceCodeEditorViewProxy(XVim) xvim_syncStateWithScroll:] + 141 (SourceCodeEditorViewProxy+XVim.m:173)
5   net.JugglerShu.XVim2          	0x0000000127a44cfb -[SourceCodeEditorViewProxy(Operations) xvim_delete:withMotionPoint:andYank:] + 1521
6   net.JugglerShu.XVim2          	0x0000000127a446ed -[SourceCodeEditorViewProxy(Operations) xvim_delete:andYank:] + 77 (SourceCodeEditorViewProxy+Operations.m:41)
7   net.JugglerShu.XVim2          	0x0000000127a2cf67 -[XVimDeleteEvaluator motionFixed:] + 248 (XVimDeleteEvaluator.m:88)
8   net.JugglerShu.XVim2          	0x0000000127a2976e -[XVimMotionEvaluator _motionFixed:] + 178 (XVimMotionEvaluator.m:115)
9   net.JugglerShu.XVim2          	0x0000000127a3d7dd -[XVimOperatorEvaluator _motionFixed:] + 50 (XVimOperatorEvaluator.m:64)
10  net.JugglerShu.XVim2          	0x0000000127a2ce13 -[XVimDeleteEvaluator d] + 143 (XVimDeleteEvaluator.m:61)
11  net.JugglerShu.XVim2          	0x0000000127a6db8f -[XVimEvaluator eval:] + 75 (XVimEvaluator.m:83)
12  net.JugglerShu.XVim2          	0x0000000127a6abf8 -[XVimNumericEvaluator eval:] + 166 (XVimNumericEvaluator.m:34)
13  net.JugglerShu.XVim2          	0x0000000127a48437 -[XVimWindow handleKeyStroke:onStack:] + 434 (XVimWindow.m:232)
14  net.JugglerShu.XVim2          	0x0000000127a47d83 -[XVimWindow handleOneXVimString:] + 495 (XVimWindow.m:172)
15  net.JugglerShu.XVim2          	0x0000000127a47fd3 -[XVimWindow handleXVimString:] + 259 (XVimWindow.m:190)
16  net.JugglerShu.XVim2          	0x0000000127a47b6c -[XVimWindow handleKeyEvent:] + 391
17  net.JugglerShu.XVim2          	0x0000000127a6d690 -[XVimIDEPegasusSourceEditorView xvim_keyDown:] + 73 (_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.m:67)
18  com.apple.AppKit              	0x00007fffc9efa2cc -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 4086
19  com.apple.AppKit              	0x00007fffc9ef8f0a -[NSWindow(NSEventRouting) sendEvent:] + 541
20  com.apple.dt.IDEKit           	0x00000001110515d5 -[IDEWorkspaceWindow sendEvent:] + 154
21  com.apple.AppKit              	0x00007fffc9d7e4a8 -[NSApplication(NSEvent) sendEvent:] + 4768
22  com.apple.dt.IDEKit           	0x000000011109bb03 -[IDEApplication sendEvent:] + 921
23  com.apple.AppKit              	0x00007fffc95f8427 -[NSApplication run] + 1002
24  com.apple.AppKit              	0x00007fffc95c2e0e NSApplicationMain + 1237
25  libdyld.dylib                 	0x00007fffe1292235 start + 1
```

**Comment by pman215** [comment] 2017-10-12 23:12
After debugging a bit more this may be related to the fix for https://github.com/XVimProject/XVim2/issues/11. 

If you try to delete the last two line in the file nothing happens. Please let me know if this is related or should file a new bug for the inability to delete last two lines.

**Comment by antmd** [comment] 2017-10-13 11:03
Hi. I pushed a fix for not being able to delete the last line. In fact, Xcode 9 *always* has a last blank line, so you can't delete it, but the special handling for 'last line' delete needed to change so that it applied to the second-from-last line instead.

This probably won't fix the crash, though, so the issue remains open.

**Comment by pebble8888** [comment] 2019-03-21 13:35
I can't reproduce the issue.
Please reopen it if you have a problem.

**Closed by pebble8888** 2019-03-21 13:35 UTC
Labels: CRASH, bug
